import Head from 'next/head';
import { Container } from '@chakra-ui/react';
import Header from '@components/Header';
import Main from '@components/Main';
import Footer from '@components/Footer';

const DefaultLayout = ({ children }) => (
  <Container bg="gray.100" maxW="container.lg">
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header />

    <Main>{children}</Main>

    <Footer />
  </Container>
);

export default DefaultLayout;
